// Bundles editor-web/ into src/editorHtml.ts (one string the WebView loads).
// Run automatically before `npm start`; re-run after changing editor-web/ or packages/live-editor/.
import { build } from "vite";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
await build({ configFile: resolve(root, "editor-web/vite.config.ts"), logLevel: "warn" });

const dist = resolve(root, "editor-web/dist");
const js = readFileSync(resolve(dist, "editor.js"), "utf8");
const css = readdirSync(dist)
  .filter((f) => f.endsWith(".css"))
  .map((f) => readFileSync(resolve(dist, f), "utf8"))
  .join("\n");
// Inline scripts need two escapes: `</script` would end the script early, and `<!--` followed later by
// `<script` puts the HTML parser in a state where the real `</script>` no longer ends it (the plugin
// host's code contains both). `\/` and `\!` mean the same as `/` and `!` in strings and regexes.
const safeJs = js.replaceAll("</script", "<\\/script").replaceAll("<!--", "<\\!--");
const html = readFileSync(resolve(root, "editor-web/index.html"), "utf8")
  .replace("/*__CSS__*/", () => css)
  .replace("/*__JS__*/", () => safeJs);

writeFileSync(
  resolve(root, "src/editorHtml.ts"),
  `// GENERATED by scripts/build-editor.mjs — do not edit.\nexport const EDITOR_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`editorHtml.ts written (${(html.length / 1024).toFixed(0)} KB)`);
