// Bundles examples/plugins/* into src/pluginCatalog.ts, the list the phone's plugin Store installs from.
// Metro can't glob folders outside the app, so this generates it (like build-editor.mjs). Runs before `npm start`.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const plugins = resolve(root, "../../examples/plugins");
const entries = [];
for (const id of readdirSync(plugins).sort()) {
  const manifest = resolve(plugins, id, "manifest.json");
  const main = resolve(plugins, id, "main.js");
  if (!existsSync(manifest) || !existsSync(main)) continue;
  entries.push({ manifestText: readFileSync(manifest, "utf8"), code: readFileSync(main, "utf8") });
}
writeFileSync(
  resolve(root, "src/pluginCatalog.ts"),
  `// GENERATED by scripts/build-catalog.mjs — do not edit.\nexport const CATALOG_FILES: { manifestText: string; code: string }[] = ${JSON.stringify(entries)};\n`,
);
console.log(`pluginCatalog.ts written (${entries.length} plugins)`);
