// Bundles examples/plugins/* into src/pluginCatalog.ts, the list the phone's plugin Store installs from.
// Metro can't glob folders outside the app, so this generates it (like build-editor.mjs). Runs before `npm start`.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const plugins = resolve(root, "../../examples/plugins");
const entries = [];
for (const id of readdirSync(plugins).sort()) {
  const manifest = resolve(plugins, id, "manifest.json");
  const main = resolve(plugins, id, "main.js");
  if (!existsSync(manifest) || !existsSync(main)) continue;
  const shotsDir = resolve(plugins, id, "screenshots");
  const shots = existsSync(shotsDir) ? readdirSync(shotsDir).filter((f) => /\.(png|jpe?g|webp)$/i.test(f)).sort() : [];
  entries.push({ manifestText: readFileSync(manifest, "utf8"), code: readFileSync(main, "utf8"), shots: shots.map((f) => `../../../examples/plugins/${id}/screenshots/${f}`) });
}
// Pictures are `require`d (Metro bundles them), so the entries are written as code, not JSON.
const body = entries
  .map((e) => `{ manifestText: ${JSON.stringify(e.manifestText)}, code: ${JSON.stringify(e.code)}, screenshots: [${e.shots.map((f) => `require(${JSON.stringify(f)})`).join(", ")}] }`)
  .join(",\n  ");
writeFileSync(
  resolve(root, "src/pluginCatalog.ts"),
  `// GENERATED by scripts/build-catalog.mjs — do not edit.\nimport type { ImageSourcePropType } from 'react-native';\nexport const CATALOG_FILES: { manifestText: string; code: string; screenshots: ImageSourcePropType[] }[] = [\n  ${body},\n];\n`,
);
console.log(`pluginCatalog.ts written (${entries.length} plugins)`);
