// Bundles pdf-web/ into src/pdfHtml.ts (one string the WebView loads).
import { build } from "vite";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
await build({ configFile: resolve(root, "pdf-web/vite.config.ts"), logLevel: "warn" });

const dist = resolve(root, "pdf-web/dist");
const js = readFileSync(resolve(dist, "reader.js"), "utf8");
const css = readdirSync(dist)
  .filter((f) => f.endsWith(".css"))
  .map((f) => readFileSync(resolve(dist, f), "utf8"))
  .join("\n");

// Inline scripts need two escapes: `</script` would end the script early, and `<!--`
const safeJs = js.replaceAll("</script", "<\\/script").replaceAll("<!--", "<\\!--");
const html = readFileSync(resolve(root, "pdf-web/index.html"), "utf8")
  .replace("/*__CSS__*/", () => css)
  .replace("/*__JS__*/", () => safeJs);

writeFileSync(
  resolve(root, "src/pdfHtml.ts"),
  `// GENERATED by scripts/build-pdf.mjs — do not edit.\nexport const PDF_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`pdfHtml.ts written (${(html.length / 1024).toFixed(0)} KB)`);
